// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.5
// source: customers/events.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EventTypeUnknown             EventType = 0
	EventType_EventTypeCreated             EventType = 1
	EventType_EventTypeUpdated             EventType = 2
	EventType_EventTypeDeleted             EventType = 3
	EventType_EventTypeVerified            EventType = 4
	EventType_EventTypeBanned              EventType = 5
	EventType_EventTypeUnbanned            EventType = 6
	EventType_EventTypeSignup              EventType = 7
	EventType_EventTypeGemerateKey         EventType = 8
	EventType_EventTypeDeleteKey           EventType = 9
	EventType_EventTypeTopUp               EventType = 10
	EventType_EventTypeAddPaymentMethod    EventType = 11
	EventType_EventTypeDeletePaymentMethod EventType = 12
	EventType_EventTypePasswordReset       EventType = 13
	EventType_EventTypeLogin               EventType = 14
	EventType_EventTypeLogout              EventType = 15
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EventTypeUnknown",
		1:  "EventTypeCreated",
		2:  "EventTypeUpdated",
		3:  "EventTypeDeleted",
		4:  "EventTypeVerified",
		5:  "EventTypeBanned",
		6:  "EventTypeUnbanned",
		7:  "EventTypeSignup",
		8:  "EventTypeGemerateKey",
		9:  "EventTypeDeleteKey",
		10: "EventTypeTopUp",
		11: "EventTypeAddPaymentMethod",
		12: "EventTypeDeletePaymentMethod",
		13: "EventTypePasswordReset",
		14: "EventTypeLogin",
		15: "EventTypeLogout",
	}
	EventType_value = map[string]int32{
		"EventTypeUnknown":             0,
		"EventTypeCreated":             1,
		"EventTypeUpdated":             2,
		"EventTypeDeleted":             3,
		"EventTypeVerified":            4,
		"EventTypeBanned":              5,
		"EventTypeUnbanned":            6,
		"EventTypeSignup":              7,
		"EventTypeGemerateKey":         8,
		"EventTypeDeleteKey":           9,
		"EventTypeTopUp":               10,
		"EventTypeAddPaymentMethod":    11,
		"EventTypeDeletePaymentMethod": 12,
		"EventTypePasswordReset":       13,
		"EventTypeLogin":               14,
		"EventTypeLogout":              15,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_customers_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_customers_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{0}
}

// Event holds the customer object plus event specific data in the respective field
type Event struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type                EventType            `protobuf:"varint,1,opt,name=type,proto3,enum=events.EventType" json:"type,omitempty"`
	Customer            *Customer            `protobuf:"bytes,2,opt,name=customer,proto3" json:"customer,omitempty"`
	CallerId            string               `protobuf:"bytes,3,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	Created             *Created             `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated             *Updated             `protobuf:"bytes,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Deleted             *Deleted             `protobuf:"bytes,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Verified            *Verified            `protobuf:"bytes,7,opt,name=verified,proto3" json:"verified,omitempty"`
	Banned              *Banned              `protobuf:"bytes,8,opt,name=banned,proto3" json:"banned,omitempty"`
	Unbanned            *Unbanned            `protobuf:"bytes,9,opt,name=unbanned,proto3" json:"unbanned,omitempty"`
	Signup              *Signup              `protobuf:"bytes,10,opt,name=signup,proto3" json:"signup,omitempty"`
	GenerateKey         *GenerateKey         `protobuf:"bytes,11,opt,name=generate_key,json=generateKey,proto3" json:"generate_key,omitempty"`
	DeleteKey           *DeleteKey           `protobuf:"bytes,12,opt,name=delete_key,json=deleteKey,proto3" json:"delete_key,omitempty"`
	TopUp               *TopUp               `protobuf:"bytes,13,opt,name=top_up,json=topUp,proto3" json:"top_up,omitempty"`
	AddPaymentMethod    *AddPaymentMethod    `protobuf:"bytes,14,opt,name=add_payment_method,json=addPaymentMethod,proto3" json:"add_payment_method,omitempty"`
	DeletePaymentMethod *DeletePaymentMethod `protobuf:"bytes,15,opt,name=delete_payment_method,json=deletePaymentMethod,proto3" json:"delete_payment_method,omitempty"`
	PasswordReset       *PasswordReset       `protobuf:"bytes,16,opt,name=password_reset,json=passwordReset,proto3" json:"password_reset,omitempty"`
	Login               *Login               `protobuf:"bytes,17,opt,name=login,proto3" json:"login,omitempty"`
	Logout              *Logout              `protobuf:"bytes,18,opt,name=logout,proto3" json:"logout,omitempty"`
}

func (x *Event) Reset() {
	*x = Event{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EventTypeUnknown
}

func (x *Event) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *Event) GetCallerId() string {
	if x != nil {
		return x.CallerId
	}
	return ""
}

func (x *Event) GetCreated() *Created {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Event) GetUpdated() *Updated {
	if x != nil {
		return x.Updated
	}
	return nil
}

func (x *Event) GetDeleted() *Deleted {
	if x != nil {
		return x.Deleted
	}
	return nil
}

func (x *Event) GetVerified() *Verified {
	if x != nil {
		return x.Verified
	}
	return nil
}

func (x *Event) GetBanned() *Banned {
	if x != nil {
		return x.Banned
	}
	return nil
}

func (x *Event) GetUnbanned() *Unbanned {
	if x != nil {
		return x.Unbanned
	}
	return nil
}

func (x *Event) GetSignup() *Signup {
	if x != nil {
		return x.Signup
	}
	return nil
}

func (x *Event) GetGenerateKey() *GenerateKey {
	if x != nil {
		return x.GenerateKey
	}
	return nil
}

func (x *Event) GetDeleteKey() *DeleteKey {
	if x != nil {
		return x.DeleteKey
	}
	return nil
}

func (x *Event) GetTopUp() *TopUp {
	if x != nil {
		return x.TopUp
	}
	return nil
}

func (x *Event) GetAddPaymentMethod() *AddPaymentMethod {
	if x != nil {
		return x.AddPaymentMethod
	}
	return nil
}

func (x *Event) GetDeletePaymentMethod() *DeletePaymentMethod {
	if x != nil {
		return x.DeletePaymentMethod
	}
	return nil
}

func (x *Event) GetPasswordReset() *PasswordReset {
	if x != nil {
		return x.PasswordReset
	}
	return nil
}

func (x *Event) GetLogin() *Login {
	if x != nil {
		return x.Login
	}
	return nil
}

func (x *Event) GetLogout() *Logout {
	if x != nil {
		return x.Logout
	}
	return nil
}

type Customer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status  string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // awaiting_verification, verified, active, inactive
	Created int64  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Email   string `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Updated int64  `protobuf:"varint,7,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *Customer) Reset() {
	*x = Customer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{1}
}

func (x *Customer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Customer) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Customer) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

type Created struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Created) Reset() {
	*x = Created{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Created) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Created) ProtoMessage() {}

func (x *Created) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Created.ProtoReflect.Descriptor instead.
func (*Created) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{2}
}

type Updated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Updated) Reset() {
	*x = Updated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Updated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Updated) ProtoMessage() {}

func (x *Updated) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Updated.ProtoReflect.Descriptor instead.
func (*Updated) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{3}
}

type Deleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Deleted) Reset() {
	*x = Deleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Deleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Deleted) ProtoMessage() {}

func (x *Deleted) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Deleted.ProtoReflect.Descriptor instead.
func (*Deleted) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{4}
}

type Verified struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Verified) Reset() {
	*x = Verified{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Verified) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Verified) ProtoMessage() {}

func (x *Verified) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Verified.ProtoReflect.Descriptor instead.
func (*Verified) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{5}
}

type Banned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Banned) Reset() {
	*x = Banned{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Banned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banned) ProtoMessage() {}

func (x *Banned) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banned.ProtoReflect.Descriptor instead.
func (*Banned) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{6}
}

type Unbanned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Unbanned) Reset() {
	*x = Unbanned{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unbanned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unbanned) ProtoMessage() {}

func (x *Unbanned) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unbanned.ProtoReflect.Descriptor instead.
func (*Unbanned) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{7}
}

type Signup struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// github/google/email
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *Signup) Reset() {
	*x = Signup{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Signup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signup) ProtoMessage() {}

func (x *Signup) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signup.ProtoReflect.Descriptor instead.
func (*Signup) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{8}
}

func (x *Signup) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type GenerateKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GenerateKey) Reset() {
	*x = GenerateKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKey) ProtoMessage() {}

func (x *GenerateKey) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKey.ProtoReflect.Descriptor instead.
func (*GenerateKey) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{9}
}

type DeleteKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteKey) Reset() {
	*x = DeleteKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKey) ProtoMessage() {}

func (x *DeleteKey) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKey.ProtoReflect.Descriptor instead.
func (*DeleteKey) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{10}
}

type TopUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount int64 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *TopUp) Reset() {
	*x = TopUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TopUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUp) ProtoMessage() {}

func (x *TopUp) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUp.ProtoReflect.Descriptor instead.
func (*TopUp) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{11}
}

func (x *TopUp) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type AddPaymentMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddPaymentMethod) Reset() {
	*x = AddPaymentMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPaymentMethod) ProtoMessage() {}

func (x *AddPaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPaymentMethod.ProtoReflect.Descriptor instead.
func (*AddPaymentMethod) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{12}
}

type DeletePaymentMethod struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePaymentMethod) Reset() {
	*x = DeletePaymentMethod{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePaymentMethod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePaymentMethod) ProtoMessage() {}

func (x *DeletePaymentMethod) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePaymentMethod.ProtoReflect.Descriptor instead.
func (*DeletePaymentMethod) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{13}
}

type PasswordReset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PasswordReset) Reset() {
	*x = PasswordReset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordReset) ProtoMessage() {}

func (x *PasswordReset) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordReset.ProtoReflect.Descriptor instead.
func (*PasswordReset) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{14}
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// github/google/email
	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{15}
}

func (x *Login) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type Logout struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Logout) Reset() {
	*x = Logout{}
	if protoimpl.UnsafeEnabled {
		mi := &file_customers_events_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Logout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Logout) ProtoMessage() {}

func (x *Logout) ProtoReflect() protoreflect.Message {
	mi := &file_customers_events_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Logout.ProtoReflect.Descriptor instead.
func (*Logout) Descriptor() ([]byte, []int) {
	return file_customers_events_proto_rawDescGZIP(), []int{16}
}

var File_customers_events_proto protoreflect.FileDescriptor

var file_customers_events_proto_rawDesc = []byte{
	0x0a, 0x16, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x73, 0x2f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x22, 0xda, 0x06, 0x0a, 0x05, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x2c, 0x0a, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x75, 0x73,
	0x74, 0x6f, 0x6d, 0x65, 0x72, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x52, 0x07,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x52, 0x07, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x2c, 0x0a,
	0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x52, 0x08, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x62,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x2e, 0x42, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x06, 0x62, 0x61, 0x6e,
	0x6e, 0x65, 0x64, 0x12, 0x2c, 0x0a, 0x08, 0x75, 0x6e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x55,
	0x6e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x52, 0x08, 0x75, 0x6e, 0x62, 0x61, 0x6e, 0x6e, 0x65,
	0x64, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x75,
	0x70, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x36, 0x0a, 0x0c, 0x67, 0x65, 0x6e,
	0x65, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x52, 0x0b, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x30, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x06, 0x74, 0x6f, 0x70, 0x5f, 0x75, 0x70, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x54, 0x6f, 0x70,
	0x55, 0x70, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x55, 0x70, 0x12, 0x46, 0x0a, 0x12, 0x61, 0x64, 0x64,
	0x5f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18,
	0x0e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52,
	0x10, 0x61, 0x64, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x12, 0x4f, 0x0a, 0x15, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x70, 0x61, 0x79, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x13, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x12, 0x3c, 0x0a, 0x0e, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x72,
	0x65, 0x73, 0x65, 0x74, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x65,
	0x74, 0x52, 0x0d, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74,
	0x12, 0x23, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x11, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x05,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x18,
	0x12, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x4c,
	0x6f, 0x67, 0x6f, 0x75, 0x74, 0x52, 0x06, 0x6c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x22, 0x7c, 0x0a,
	0x08, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x09, 0x0a, 0x07, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0x09, 0x0a, 0x07, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x22, 0x09, 0x0a, 0x07, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x22, 0x0a, 0x0a, 0x08,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x22, 0x08, 0x0a, 0x06, 0x42, 0x61, 0x6e, 0x6e,
	0x65, 0x64, 0x22, 0x0a, 0x0a, 0x08, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x22, 0x20,
	0x0a, 0x06, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x22, 0x0d, 0x0a, 0x0b, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22,
	0x0b, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x1f, 0x0a, 0x05,
	0x54, 0x6f, 0x70, 0x55, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x12, 0x0a,
	0x10, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x0f, 0x0a, 0x0d, 0x50, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x65, 0x74, 0x22, 0x1f, 0x0a, 0x05, 0x4c, 0x6f, 0x67,
	0x69, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x08, 0x0a, 0x06, 0x4c, 0x6f,
	0x67, 0x6f, 0x75, 0x74, 0x2a, 0x87, 0x03, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x55,
	0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x10, 0x01, 0x12, 0x14,
	0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x10, 0x03, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x10,
	0x04, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x61,
	0x6e, 0x6e, 0x65, 0x64, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x55, 0x6e, 0x62, 0x61, 0x6e, 0x6e, 0x65, 0x64, 0x10, 0x06, 0x12, 0x13, 0x0a,
	0x0f, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x75, 0x70,
	0x10, 0x07, 0x12, 0x18, 0x0a, 0x14, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x47,
	0x65, 0x6d, 0x65, 0x72, 0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b,
	0x65, 0x79, 0x10, 0x09, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x54, 0x6f, 0x70, 0x55, 0x70, 0x10, 0x0a, 0x12, 0x1d, 0x0a, 0x19, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x41, 0x64, 0x64, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x10, 0x0b, 0x12, 0x20, 0x0a, 0x1c, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x10, 0x0c, 0x12, 0x1a, 0x0a, 0x16, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x65, 0x74, 0x10, 0x0d, 0x12, 0x12, 0x0a, 0x0e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x10, 0x0e, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x4c, 0x6f, 0x67, 0x6f, 0x75, 0x74, 0x10, 0x0f, 0x42, 0x10,
	0x5a, 0x0e, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_customers_events_proto_rawDescOnce sync.Once
	file_customers_events_proto_rawDescData = file_customers_events_proto_rawDesc
)

func file_customers_events_proto_rawDescGZIP() []byte {
	file_customers_events_proto_rawDescOnce.Do(func() {
		file_customers_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_customers_events_proto_rawDescData)
	})
	return file_customers_events_proto_rawDescData
}

var file_customers_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_customers_events_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_customers_events_proto_goTypes = []interface{}{
	(EventType)(0),              // 0: events.EventType
	(*Event)(nil),               // 1: events.Event
	(*Customer)(nil),            // 2: events.Customer
	(*Created)(nil),             // 3: events.Created
	(*Updated)(nil),             // 4: events.Updated
	(*Deleted)(nil),             // 5: events.Deleted
	(*Verified)(nil),            // 6: events.Verified
	(*Banned)(nil),              // 7: events.Banned
	(*Unbanned)(nil),            // 8: events.Unbanned
	(*Signup)(nil),              // 9: events.Signup
	(*GenerateKey)(nil),         // 10: events.GenerateKey
	(*DeleteKey)(nil),           // 11: events.DeleteKey
	(*TopUp)(nil),               // 12: events.TopUp
	(*AddPaymentMethod)(nil),    // 13: events.AddPaymentMethod
	(*DeletePaymentMethod)(nil), // 14: events.DeletePaymentMethod
	(*PasswordReset)(nil),       // 15: events.PasswordReset
	(*Login)(nil),               // 16: events.Login
	(*Logout)(nil),              // 17: events.Logout
}
var file_customers_events_proto_depIdxs = []int32{
	0,  // 0: events.Event.type:type_name -> events.EventType
	2,  // 1: events.Event.customer:type_name -> events.Customer
	3,  // 2: events.Event.created:type_name -> events.Created
	4,  // 3: events.Event.updated:type_name -> events.Updated
	5,  // 4: events.Event.deleted:type_name -> events.Deleted
	6,  // 5: events.Event.verified:type_name -> events.Verified
	7,  // 6: events.Event.banned:type_name -> events.Banned
	8,  // 7: events.Event.unbanned:type_name -> events.Unbanned
	9,  // 8: events.Event.signup:type_name -> events.Signup
	10, // 9: events.Event.generate_key:type_name -> events.GenerateKey
	11, // 10: events.Event.delete_key:type_name -> events.DeleteKey
	12, // 11: events.Event.top_up:type_name -> events.TopUp
	13, // 12: events.Event.add_payment_method:type_name -> events.AddPaymentMethod
	14, // 13: events.Event.delete_payment_method:type_name -> events.DeletePaymentMethod
	15, // 14: events.Event.password_reset:type_name -> events.PasswordReset
	16, // 15: events.Event.login:type_name -> events.Login
	17, // 16: events.Event.logout:type_name -> events.Logout
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_customers_events_proto_init() }
func file_customers_events_proto_init() {
	if File_customers_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_customers_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Event); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Customer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Created); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Updated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Deleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Verified); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Banned); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unbanned); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Signup); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TopUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPaymentMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePaymentMethod); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordReset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_customers_events_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Logout); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_customers_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_customers_events_proto_goTypes,
		DependencyIndexes: file_customers_events_proto_depIdxs,
		EnumInfos:         file_customers_events_proto_enumTypes,
		MessageInfos:      file_customers_events_proto_msgTypes,
	}.Build()
	File_customers_events_proto = out.File
	file_customers_events_proto_rawDesc = nil
	file_customers_events_proto_goTypes = nil
	file_customers_events_proto_depIdxs = nil
}
